[def.relational-default]
topic = "Relational test"
model = "relational"
entity = "relational"
filter.topic = "relational"
mapping.relational = [
    {name = "TEXT"}, {age = "INT"}
]
processing = "SELECT age + 3 FROM $" # INSERT INTO $target SELECT age + 3 FROM $source
# db.$.aggregate([$project: { age: ["$age", 3] }])
# MATCH (n:$) CREATE (n {age:age + 3})

# MATCH (template:$source)
# WITH properties(template) AS props
# CREATE (newTask:$target)
# SET newTask = props

#window = "HOPPING (SIZE 30 SECONDS, ADVANCE BY 10 SECONDS)"

[def.document-default]
topic = "Document test"
model = "document"
entity = "document"
filter.topic = "doc"
mapping.document = "document"
processing = "db.$.find({age: 1})"
# SELECT age FROM $source
# MATCH (n:$) RETURN n.age

[def.graph-default]
topic = "Graph test"
model = "graph"
entity = "graph"
filter.topic = "graph"
processing = "MATCH (n:$:Person) RETURN n.age"
# SELECT age FROM $ WHERE label = "Person"
# db.$.aggregate([$filter: { label: "Person" }])
[def.graph-default.mapping.graph.node]
id = {doc.key = "id"}
label = {doc.key = "label"}
properties = {doc.key = "properties"}



