[package]
name = "macro"
version = "1.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
quote = "1.0"
syn = { version = "2.0.106", features = ["full"] }

[lib]
proc-macro = true