name: Release
permissions:
  "contents": "write"

on:
  pull_request:
  push:
#   tags:
# - '**[0-9]+.[0-9]+.[0-9]+*' // is version

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ending: exe
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Step 3: Install target for cross-compilation (Linux, macOS, Windows)
      - name: Install additional Rust targets
        run: rustup target add ${{ matrix.target }}

      # Step 4: Build the Rust project
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      # Step 5: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}.${{ matrix.ending }}
          path: target/${{ matrix.target }}/release/